src/mdapioutput/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Courseid__c</fullName>
        <label>Course id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_fees__c</fullName>
        <label>Course fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CourseContactControllerTest.cls
@isTest
public class CourseContactControllerTest {
@isTest
    public static void ContactCourseFactory(){
        list<contact> contactToBeInserted=new list<contact>();     
        for(integer i=0;i<100;i++){
            contact c=new contact();
            c.LastName='test'+i;
			contactToBeInserted.add(c);            
        }
        insert contactToBeInserted;
        list<course__c> coursesToBeInserted=new list<course__c>();
        for(integer i=0;i<100;i++){
       	 	course__c cou=new course__c();
        	cou.contact__c=contactToBeInserted[0].id;
            cou.Course_fees__c=100;
            cou.Courseid__c='124'+i;
            cou.Name='test'+i;
        coursesToBeInserted.add(cou);
            }
        insert coursesToBeInserted;
    
     CourseContactController.getContacts();
        list<Course__c> corList= CourseContactController.getCoursesOfContact(contactToBeInserted[0].id);
        System.assertEquals(corList.size(), 100);
        
        course__c course=coursesToBeInserted[0];
        course.Course_fees__c=200;
        CourseContactController.upsertCourse(course);
        CourseContactController.deleteCourse(course.id);
        
        
       
    }    
    

}