src/mdapioutput/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_fees__c</fullName>
        <label>Course fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CourseContactController.cls
public class CourseContactController {
    
    @AuraEnabled
    public static List<Contact> getContacts(){
        list<Contact> conList=[SELECT Id,Name FROM Contact];
        
        System.debug(conList);
        return conList;
    }
    
    @AuraEnabled
    public static List<Course__c> getCoursesOfContact(String contactId){
        return [select Contact__c,Course_fees__c,Course__c,Name from Course__c where Contact__c=:contactId];
    }  
    
    @AuraEnabled
    public static Course__c upsertCourse(Course__c cor){
        upsert cor;
        return cor;
    }
    /*
    @AuraEnabled
    public static void markTasksAsCompleted(List<Contact> cons){
        update cons;
    }
    */
    @AuraEnabled
    public static void deleteCourse(String corId){
        delete new Course__c(id=corId);
    }
    
}